version: '3'

services:
  # PostgreSQL service
  db:
    image: postgres:16-alpine3.18
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Rails app service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    volumes:
      - .:/app

volumes:
  postgres_data:
